### ISSUE TITLE
Is there any way to trigger this when an event is added, updated or deleted?

### ISSUE THREAD

**Issue by kelvinalfaro** [MShekow/outlook-google-calendar-sync#1]
Hi, I have a similar flow running that triggers "When an event is added, updated or deleted (V3)" and it syncs.  is there a way to make that the trigger for your version? I appreciate the more polished approach your flow takes. Any advice would be helpful

**Comment by MShekow** [comment]
While technically possible, doing so would **not** be advisable. My flow takes a long time to complete (several minutes) and consumes many actions of your daily quota, which is why the trigger in my flow is configured to only fire a few times per day. The "When an event is added, updated or deleted (V3)" trigger is executed rather often throughout the day (it is also fired when you have Outlook open and an event reminder is fired), making it too resource-hungry.
